name: bard
description: "Bard - Your Personal Music Assistant"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.10.0
  curved_navigation_bar: ^1.0.3
  page_transition: ^2.0.9
  flutter_map: ^7.0.2
  firebase_messaging: ^15.2.0
  latlong2: ^0.9.1
  googleapis_auth: ^1.5.1
  jose: ^0.3.4
  pdf: ^3.8.0
  printing: ^5.9.0
  flutter_secure_storage: ^10.0.0-beta.4
  firebase_auth: ^5.4.0
  firebase_database: ^11.3.0
  animated_notch_bottom_bar: ^1.0.3
  flutter_svg: ^2.0.10+1
  provider: ^6.0.5
  url_launcher: ^6.0.9
  image_picker: ^1.0.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.1
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.0.0
  animations: ^2.0.0
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  smooth_page_indicator: ^1.0.0+2
  motion_tab_bar: ^2.0.4
  motion_tab_bar_v2: ^0.3.0
  win32: ^5.8.0
  carousel_slider: ^5.0.0
  device_info_plus: ^11.2.0
  uuid: ^4.5.1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.7
  supabase_flutter: ^2.8.3
  path: ^1.8.0
  flutter_fortune_wheel: ^1.2.0
  bitsdojo_window: ^0.1.6
  percent_indicator: ^4.2.2
  flutter_staggered_grid_view: ^0.6.2
  fl_chart: ^0.63.0
  image: ^4.0.17
  charts_flutter: ^0.12.0
  confetti: ^0.7.0


  flutter_localizations:
    sdk: flutter
dependency_overrides:
  intl: ^0.20.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0



flutter:



  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/a1.png
    - images/a2.png
    - images/w1.gif
    - images/k.png
    - images/t1.jpg
    - images/back.gif
    - images/black1.gif
    - assets/icons/icon.png
    - images/s1.gif




flutter_icons:
  android: true
  ios: true
  windows:
    generate: true
  image_path: "assets/icons/icon.png"
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
