// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg2bS-Q352ULY3HQjlcQzzosvVyRqWDQI',
    appId: '1:406177196165:web:18e83f09eb799add2661ec',
    messagingSenderId: '406177196165',
    projectId: 'bard-bfaf2',
    authDomain: 'bard-bfaf2.firebaseapp.com',
    storageBucket: 'bard-bfaf2.appspot.com',
    measurementId: 'G-5K4MBH89G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUrbVQlFxLpuy2OIEBcFQuyqAGUWwEAOA',
    appId: '1:406177196165:android:1f727346c94897112661ec',
    messagingSenderId: '406177196165',
    projectId: 'bard-bfaf2',
    storageBucket: 'bard-bfaf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7ntW7QOuPk9CoMU5EFD7lnhxpNNJG38',
    appId: '1:406177196165:ios:b19410f3598f64bc2661ec',
    messagingSenderId: '406177196165',
    projectId: 'bard-bfaf2',
    storageBucket: 'bard-bfaf2.appspot.com',
    iosBundleId: 'com.laith.bard.bard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX7ntW7QOuPk9CoMU5EFD7lnhxpNNJG38',
    appId: '1:406177196165:ios:b19410f3598f64bc2661ec',
    messagingSenderId: '406177196165',
    projectId: 'bard-bfaf2',
    storageBucket: 'bard-bfaf2.appspot.com',
    iosBundleId: 'com.laith.bard.bard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg2bS-Q352ULY3HQjlcQzzosvVyRqWDQI',
    appId: '1:406177196165:web:110cd313b993cdec2661ec',
    messagingSenderId: '406177196165',
    projectId: 'bard-bfaf2',
    authDomain: 'bard-bfaf2.firebaseapp.com',
    storageBucket: 'bard-bfaf2.appspot.com',
    measurementId: 'G-SK2HXZ4RHF',
  );
}
